<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
    $grid = MAGE::helper('ThemeOptions')->getThemeOptions('grid' );
	
	$category = Mage::registry('current_category');
    if ($category) {
      $catId =  $category->getId();
      $staticBlock = trim($this->getLayout()->createBlock('cms/block')->setBlockId('category_slider_' . $catId)->toHtml());
    }
?>

<?php 
$catId = 13;
echo $staticBlock = trim($this->getLayout()->createBlock('cms/block')->setBlockId('category_slider_' . $catId)->toHtml()); 
?>

<?php if (Mage::app()->getFrontController()->getRequest()->getControllerName() == 'category' and $staticBlock): ?>
        <div class="category-slider-container">
    <div class="iosSlider">
        <?php
        if(!empty($staticBlock)){
            echo $staticBlock;
        }
        ?>
    <div class="container_12">
        <div class = 'next'></div>
        <div class = 'prev unselectable'></div>
    </div>
    </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery('.iosSlider').iosSlider({
      responsiveSlideWidth: true,
      snapToChildren: true,
      desktopClickDrag: true,
      infiniteSlider: true,
      navSlideSelector: '.slideSelectors .button-item',
      navNextSelector: '.iosSlider .next',
      navPrevSelector: '.iosSlider .prev',
      onSlideComplete: slideComplete,
      onSliderLoaded: sliderLoaded,
      onSlideChange: slideChange
    });
    
    
    function slideChange(args) {
        jQuery('.slideSelectors .button-item').removeClass('selected');
        jQuery('.slideSelectors .button-item:eq(' + args.currentSlideNumber + ')').addClass('selected');
    }
    
    function slideComplete(args) {
            
          /* Animation */
          jQuery(args.sliderObject).find('h2').attr('style', '');   
          jQuery(args.sliderObject).find('p.container_12').attr('style', '');
          
          /* left caption */
          if(jQuery(args.currentSlideObject).hasClass('left-caption')){
            jQuery(args.currentSlideObject).children('h2').animate({
                left: '50%',
                opacity: '1'
              }, 500, 'easeOutQuint');
          }
          if(jQuery(args.currentSlideObject).hasClass('left-caption')){
            jQuery(args.currentSlideObject).children('p.container_12').animate({
                left: '50%',
                opacity: '1'
              }, 950, 'easeOutQuint');
          }
         
         /* right caption */
         if(jQuery(args.currentSlideObject).hasClass('right-caption')){
            jQuery(args.currentSlideObject).children('h2').animate({
                right: '50%',
                opacity: '1'
              }, 500, 'easeOutQuint');
          }
          if(jQuery(args.currentSlideObject).hasClass('right-caption')){
            jQuery(args.currentSlideObject).children('p.container_12').animate({
                right: '50%',
                opacity: '1'
              }, 950, 'easeOutQuint');
          } 
            
      }
    
    function sliderLoaded(args) {
        slideComplete(args);
        slideChange(args);
    }
    
    jQuery('.iosSlider div.item').each(function(){
        jQuery(this).css('backgroundImage', 'url('+ jQuery(this).find('a img').attr('src') +')');
    });
    
    jQuery('.content-wrapper').addClass('category-slider');
    
  });
</script>
    <?php endif; ?>
	
	
	
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<section class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
	<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <div class="grid_3 alpha">
                <div class="product-img-box">
					<?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 420); ?></div></a>
                    <?php // Fancybox
                    if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                        <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
                    <?php endif; // End Fancybox ?>                    
                </div>
            </div>
            <?php // Product description ?>
            <div class="grid_6 omega">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>                
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                <?php endif; ?>
                <?php if(!$_product->isSaleable()): ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                <div class="clear"></div>
                <div class="desc std">
                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                </div>
				<?php echo $this->getPriceHtml($_product, true) ?>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
                <?php if($_product->isSaleable()): ?>
                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>                                    
                <?php endif; ?>
            </div>            
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>


    <?php if ($grid == 'grid_large'): //////// Grid Large ?>

    <ul class="products-grid large-grid">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="grid_3 item">
				<div class="product-img-box">
					<?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(410, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 410); ?></div></a>
					<?php  // Fancybox
					if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
							<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
						<?php endif;
					// End Fancybox ?>
				</div>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>                        
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="clear"></div>
            </li>
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>        

    <?php elseif ($grid == 'grid_standard'): //////// Standard Grid ?>
    
    <ul class="products-grid">
    <?php $i=1; foreach ($_productCollection as $_product): ?>
	<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="grid_3 item">
				<div class="product-img-box">
					<?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 420); ?></div></a>
					<?php  // Fancybox
					if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
							<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
						<?php endif;
					// End Fancybox ?>
				</div>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>                        
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="clear"></div>
            </li>
            <?php $i++; endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
    <?php elseif ($grid == 'grid_small'): ?>

    <ul class="products-grid small-grid">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="item">
				<div class="product-img-box">
					<?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 420); ?></div></a>
					<?php  // Fancybox
					if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
							<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
						<?php endif;
					// End Fancybox ?>
				</div>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>                        
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="clear"></div>
            </li>
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
    <?php endif; ///////////// Grid ?>
    <script type="text/javascript">
        jQuery(window).load(function(){
            var $container = jQuery('.products-grid');
            $container.isotope({
                itemSelector: '.item',
                resizable: true,
                layoutMode : 'fitRows'
            });
        });
    </script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</section>
<?php endif; ?>