<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<footer id="footer">
	<div class="footer-wrapper">
		<div class="container_12">
		   <div class="footer-columns-block">
				<?php // Predefined Static Block
				if ($static_html = $this->getChildHtml('custom_footer')):
					echo $static_html;
				endif; ?>
			</div>
			<!--<?php //echo $this->getChildHtml('footer.newsletter') ?>-->
			<div class="clear"></div>
			<div class="grid_12">
				<div class="footer-bottom-block">
					<?php echo $this->getChildHtml('topSearch') ?>
					<?php echo $this->getChildHtml('cms_footer_links') ?>
					<?php echo $this->getChildHtml('footer_links') ?>
					<address><?php echo $this->getCopyright() ?></address>
					
					<?php echo $this->getChildHtml('store_switcher') ?>
				</div>
			</div>
			<div class="clear"></div>
		</div> 
	</div>
</footer>