<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php
    $customlogo = MAGE::helper('ThemeOptions')->getThemeOptions('customlogo');
    $mediaurl = MAGE::helper('ThemeOptions')->getThemeOptions('mediaurl');
?>
<header id="header">
	<div class="grid_12">
		<div>
			<h1 class="heading">ESPADIM</h1>
			<h2 class="sub-header">SINCE 1958</h2>	
		</div>
		<!--<div class="quick-access">
			<?php //echo $this->getChildHtml('store_language') ?>
			<?php //echo $this->getChildHtml('currency') ?>
			<?php //echo $this->getChildHtml('topLinks') ?>
			<p class="welcome-msg"><?php //echo $this->getWelcome() ?><?php //echo $this->getAdditionalHtml() ?></p>
			<div class="clear"></div>
		</div>-->
		<!--<?php if ($customlogo['logo_status'] == 0): ?>
			<h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
			<?php else:?>
			<h1 class="logo"><strong><?php echo $customlogo['logo_alt']; ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $customlogo['logo_alt']; ?>" class="logo"><img src="<?php echo $mediaurl.$customlogo['logo']; ?>" alt="<?php echo $customlogo['logo_alt']; ?>" /></a></h1>
		<?php endif; ?>
		<!--<?php //echo $this->getChildHtml('topCart') ?>-->
		<div class="clear"></div>
		<?php if($this->getChildHtml('header_text_block')): ?>
		<div class="header-text-block">
			<?php echo $this->getChildHtml('header_text_block') ?>
		</div>
		<?php endif; ?>
		<!--<div class="header-botttom-block">
			<?php //echo $this->getChildHtml('topMenu') ?>
			<div class="menu-button"><span>&nbsp;</span><?php //echo $this->__('Menu') ?></div>
			<?php //echo $this->getChildHtml('topSearch') ?>
			<div class="clear"></div>
		</div>-->
		<?php echo $this->getChildHtml('header_slider_container') ?>
		<?php echo $this->getChildHtml('topContainer'); ?>
	</div>
	<div class="clear"></div>
</header>