<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    $_columnCount = 4; //$this->getColumnCount();
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Grid Mode ?>
<div class="home-container grid">
    <div class="meigee-widget">
        <ul class="products-grid widget-grid">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="grid_3 item">
                <div class="product-img-box">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 420); ?></a>
				<div class="img-shadow"><div><div></div></div></div>
				<a href="<?php echo $_product->getProductUrl() ?>" class="icon-product-details"></a>
				<?php // Fancybox
				if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
					<a class="fancybox" rel="category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
				<?php endif; // End Fancybox ?>
				</div>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<?php if($_product->getRatingSummary()): ?>
				<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
				<?php endif; ?>
				<div class="clear"></div>
            </li>
        <?php if ($i+1 == $_collectionSize ) break; $i++; endforeach ?>        
        </ul> 
    </div>
</div>