<?php
    $_productCollection = $this->getMyCollection();
	$gridMode = $this->sliderGridSelection();
	$visibleProducts = $this->getData('visible_products');
	$productCount = count($_productCollection);
	if (count($_productCollection)) {
	
		$category = $this->catName();
		$_helper = $this->helper('catalog/output');
		$_collectionSize = $this->productsAmount();

		$randId = $this->getWidgetId();
		
		$fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Slider ?>
<div class="slider-container widget-container">
<?php if($productCount > $visibleProducts): ?>
	<div class="home-container<?php echo ' '.$gridMode.' alpha omega'; ?>">
		<div class="home-slider-conainer">
			<div class="home-slider es-carousel-wrapper" id="home-slider-<?php echo $randId; ?>">
			<ul class="products-grid carousel-ul">
				<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<li class="item">
					<div class="product-img-box">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 420); ?></a>
					<div class="img-shadow"><div><div></div></div></div>
					<a href="<?php echo $_product->getProductUrl() ?>" class="icon-product-details"></a>
					<?php // Fancybox
					if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
						<a class="fancybox" rel="category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
					<?php endif; // End Fancybox ?>
					</div>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					<?php echo $this->getPriceHtml($_product, true) ?>
					<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php endif; ?>
					<div class="clear"></div>
				</li>
				<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
			</ul>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="clear"></div>
	<div class = 'next'><em>&nbsp;</em><span>&nbsp;</span></div>
	<div class = 'prev unselectable'><em>&nbsp;</em><span>&nbsp;</span></div>
	<?php else: ?>
		<div class="no-widget"><?php echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1) ?></div>
	<?php endif; ?>
</div>

<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#home-slider-<?php echo $randId; ?>').iosSlider({
	  responsiveSlideWidth: true,
	  snapToChildren: true,
	  desktopClickDrag: true,
	  infiniteSlider: true
	  <?php echo $this->getSliderOptions(); ?>,
	  navSlideSelector: '.sliderNavi .naviItem',
	  navNextSelector: '.widget-container .next',
	  navPrevSelector: '.widget-container .prev'
	  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
	  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
	});
  });
</script>
<?php } ?>