<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<?php 
    $cartpage = MAGE::helper('ThemeOptions')->getThemeOptions('cartpage');
?>
<div class="cart">
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
		<div class="page-title title-buttons">
			<h1><?php echo $this->__('Shopping Cart') ?></h1>
			<?php if($this->getContinueShoppingUrl()): ?>
			<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
			<?php endif; ?>
			<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-clear"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
			<button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
			<div class="clear"></div>
		</div>
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		<?php echo $this->getChildHtml('form_before') ?>
		<div class="cart-column grid_9 alpha">
			<fieldset>
				<table id="shopping-cart-table" class="data-table cart-table">
				<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
					<tbody>
					<?php foreach($this->getItems() as $_item): ?>
						<?php echo $this->getItemHtml($_item) ?>
					<?php endforeach ?>
					</tbody>
				</table>
				<script type="text/javascript">decorateTable('shopping-cart-table')</script>
			</fieldset>
		</div>
	</form>
	<div class="grid_3 omega">
		<div class="totals">
			<div class="totals-wrapper"><?php echo $this->getChildHtml('totals'); ?></div>
			<?php if(!$this->hasError()): ?>
			<ul class="checkout-types">
			<?php foreach ($this->getMethods('methods') as $method): ?>
				<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
				<li><?php echo $methodHtml; ?></li>
				<?php endif; ?>
			<?php endforeach; ?>
			</ul>
			<?php endif; ?>
        </div>
	</div>
	<div class="clear"></div>
	
    <?php if ($cartpage == 'cart_standard'): ?>
    <div class="cart-collaterals">
		<?php if($this->getChildHtml('coupon')): ?>
			<div class="grid_4 alpha">
				<?php echo $this->getChildHtml('coupon') ?>
			</div>
		<?php endif; ?>
		<?php if($this->getChildHtml('shipping')): ?>
			<div class="grid_8 omega">
				<?php echo $this->getChildHtml('shipping') ?>
			</div>
		<?php endif; ?>
		<div class="clear"></div>
		<?php echo $this->getChildHtml('crosssell_big') ?>
    </div>
    <?php else: ?>
		<div class="cart-collaterals" id="cart-accordion">
			<h3 class="accordion-title"><?php echo $this->__('Discount Codes') ?></h3>
			<div class="accordion-content"><?php echo $this->getChildHtml('coupon') ?></div>
			<?php if (!$this->getIsVirtual()):?> 
			<h3 class="accordion-title"><?php echo $this->__('Estimate Shipping and Tax') ?></h3>
			<div class="accordion-content"><?php echo $this->getChildHtml('shipping'); ?></div>
			<?php endif; ?>
			<?php if ($this->getChildHtml('crosssell')): ?>
			<h3 class="accordion-title"><?php echo $this->__('Crossel') ?></h3>
			<div class="accordion-content"><?php echo $this->getChildHtml('crosssell') ?></div>
			<?php endif; ?>
		</div>
    <?php endif; ?>
</div>
